
BINS=meter.elf 

# put here the additional .o files you want to generate
# one .c file for each .o should be present
OBJS=my_uart.o misc.o

# put here the additional header files needed for compilation
HEADERS=my_uart.h

# the file below contains the actual rules

include ../avr_common/avr.mk





